In [4]:
import pandas as pd

glucose_p_val = pd.read_csv("glucose_exploratory/glucose_pairwise_pvalues.csv")

glucose_p_val

,group_1,group_2,n_1,n_2,median_1,median_2,u_statistic,p_value,p_value_bonferroni
0,Healthy,Pre-diabetic,759,549,89.0,95.0,158005.5,8.112935e-14,4.867761e-13
1,Healthy,Oral/Non-insulin\nmed controlled,759,663,89.0,111.0,121231.5,6.334473e-64,3.800684e-63
2,Healthy,Insulin-dependent,759,246,89.0,127.0,40301.5,5.117799e-41,3.070679e-40
3,Pre-diabetic,Oral/Non-insulin\nmed controlled,549,663,95.0,111.0,117245.5,1.324597e-26,7.947579e-26
4,Pre-diabetic,Insulin-dependent,549,246,95.0,127.0,37080.5,2.604769e-24,1.562862e-23
5,Oral/Non-insulin\nmed controlled,Insulin-dependent,663,246,111.0,127.0,67342.5,5.353844e-05,3.212306e-04

In [5]:
insulin_p_val = pd.read_csv("insulin_exploratory/insulin_pairwise_pvalues.csv")

insulin_p_val

,group_1,group_2,n_1,n_2,median_1,median_2,u_statistic,p_value,p_value_bonferroni
0,Healthy,Pre-diabetic,759,549,0.48,0.580,185772.0,8.130623e-04,4.878374e-03
1,Healthy,Oral/Non-insulin\nmed controlled,759,663,0.48,0.700,191602.5,7.963154e-15,4.777893e-14
2,Healthy,Insulin-dependent,759,246,0.48,0.825,67480.5,6.125142e-11,3.675085e-10
3,Pre-diabetic,Oral/Non-insulin\nmed controlled,549,663,0.58,0.700,158224.0,8.902923e-05,5.341754e-04
4,Pre-diabetic,Insulin-dependent,549,246,0.58,0.825,55477.5,5.679588e-05,3.407753e-04
5,Oral/Non-insulin\nmed controlled,Insulin-dependent,663,246,0.70,0.825,76517.0,1.525099e-01,9.150596e-01